### ISSUE TITLE
Multiple platforms and build-tools in 1 image

### ISSUE THREAD

**Issue by tafilz** [tafilz/xamarin-android#1]
Are multiple platforms and build tools needed in 1 image?

**Comment by Ghostbird** [comment]
I assume this is a sort of _question to the community_? I'm quite happy with how the images are structured currently.

**Comment by tafilz** [comment]
> I assume this is a sort of _question to the community_? I'm quite happy with how the images are structured currently.

@Ghostbird Thanks for the comment. Yeah it was a question to the users.
