### ISSUE TITLE
Find out Xamarin.Android build number

### ISSUE THREAD

**Issue by xamadev** [tafilz/xamarin-android#2]
Hi, thanks very much for the image. I have a question about the Dockerfile . How to do you look up a newer build number like mentioned:
> # Get BUILD ID from here: https://dev.azure.com/xamarin/public/_build?definitionId=48&_a=summary

Can't find any build numbers, only commits.

**Comment by tafilz** [comment]
@xamadev 
Click on the commit you want and then check the url:
`https://dev.azure.com/xamarin/public/_build/results?buildId=31980&view=results`

You need the `buildId` part

**Comment by tafilz** [comment]
The lastest release (tag) would be build id 28462 but i think the artifacts got deleted

**Comment by tafilz** [comment]
@xamadev also checkout the latest commit 00f6551
They changed the artifact name

**Comment by xamadev** [comment]
@tafilz  Thanks for clarifying and your latest commits.

Filed an [issue here ](https://github.com/xamarin/xamarin-android/issues/5379) about the deleted artifcats. I would like to use the stable release.
